/**
 * TypeScript type declarations for smart_crop WASM module.
 * 
 * Defines the module interface for the compiled WASM binary and its
 * JavaScript wrapper generated by Emscripten.
 */

declare module "*/smart_crop.js" {
  interface WasmModuleConfig {
    // Optional path resolver for WASM binary location
    locateFile?: (path: string, scriptDirectory: string) => string;
  }

  // Factory function that returns a Promise resolving to WASM module instance
  const createModule: (config?: WasmModuleConfig) => Promise<any>;
  export default createModule;
}